### PR TITLE
Add new custom pings 🤖

### LINKED ISSUE #8: Test ping names
**Is your feature request related to a problem? Please describe.**
We recently saw a bug where custom pings that were named in `kebab-case` where being dropped by the schema at ingestion because they were invalid against the schema.  We plan to fix the schema, but it would be nice to have a test to prevent this kind of thing in the future.

**Describe the solution you'd like**
Send some custom pings with various kinds of names and make sure they are ingested correctly.

Explicitly, we should support:

- `kebab-case`
- `snake_case`
- `numbers001`

Explicitly not supported are capital letters or names over 30 characters.

**Additional context**

https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/470
https://github.com/mozilla/glean/pull/616

### PR DESCRIPTION
**Pull request by hackebrot**
Resolve #8

### CODE REVIEW

**Comment by hackebrot** [comment]
Do we need to run probe-scraper for the BigQuery tables to be created?

**Comment by fbertsch** [comment]
Indeed, these tables will be auto-deployed through the probe-scraper and MSG infrastructure.

**Review by jklukas — APPROVED** [review]

**Review by mdboom — APPROVED** [review]

**Comment by hackebrot** [comment]
Hi @fbertsch @jklukas, I can't seem to find the `starbase46_v1` and `space_ship_ready_v1` tables on the BigQuery console. Have the tables been created?

**Comment by jklukas** [comment]
Schema deployment has been blocked on a few different issues this week. It's unclear to me whether those are all resolved, but it's likely we haven't had a successful schema deploy since these new pings were merged. cc @whd

**Comment by jklukas** [comment]
There is one blocking issue that is being worked on for schema deploys. Next deploy will likely happen on Tuesday next week.

**Pull request merged**
