### PR TITLE
Bug 1734011 - Add basic set of tags to burnham

### PR DESCRIPTION
**Pull request by wlach**
This is to test the new Glean tagging feature. Not yet ready to be
merged.

### CODE REVIEW

**Comment by badboy** [comment]
#305 has the glean & glean_parser upgrade.

**Comment by wlach** [comment]
> #305 has the glean & glean_parser upgrade.

CI should start passing after these are merged

**Comment by wlach** [comment]
@hackebrot heya! This is ready for review

**Review by hackebrot — APPROVED** [review]
Hi @wlach! 👋🏻 

I haven't had a chance to study the proposal in detail, but based on my high-level understanding of the problem you're trying to solve and the conversation on Bug 1734011, the changes in your pull request look good to me!

Thank you for this pull request and my apologies for the delay in getting it reviewed. Things are a bit hectic at the moment.

LGTM! 👩🏻‍🚀

**Pull request merged**
