### PR TITLE
Set up code coverage report 🤖

### PR DESCRIPTION
**Pull request by hackebrot**
See #93

### CODE REVIEW

**Review by jklukas — APPROVED** [review]
This seems reasonable, although it's been a while since I've thought through `tox` configurations, etc. so I won't claim an entirely thorough review here.

You may be interested in setting up codecov.io to track regressions in code coverage. You should be able to get access via your GitHub account.

**Comment by hackebrot** [comment]
This currently fails on CI because the CircleCI `coverage-report` job doesn't have access to the file generated in the `py37` job. Looking at `save_cache` or other options now.

**Comment by hackebrot** [comment]
I merged the `coverage-report` tox environment into the `py37` tox environment to simplify coverage reporting. This resolves the CircleCI issue mentioned above.

I'm definitely interested in codecov tracking! For now the check will fail if the code coverage falls under 50%. We should increase that limit in #94. And then follow-up with a pull-request to integrate codecov.io.

**Review by jklukas — APPROVED** [review]

**Comment by hackebrot** [comment]
Thanks for the review @jklukas! Much appreciated. 🙇

**Pull request merged**
